### ISSUE TITLE
Pre-installed Chrome and driver not supported on Github Actions

### ISSUE THREAD

**Issue by qdequippe** [symfony/panther#349]
Hi,

I am using Github Actions to run tests with Panther but I have an error 
```
Facebook\WebDriver\Exception\SessionNotCreatedException: session not created: This version of ChromeDriver only supports Chrome version 80
```

I checked https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu2004-README.md to see software installed on virtual environnement provided by Github Actions. Chrome and Chrome driver are installed (version 83.xx) so I don't understand why I got this error.

I changed also the Chrome driver binary `PANTHER_CHROME_DRIVER_BINARY=/usr/local/share/chrome_driver` (e.g path of $CHROMEWEBDRIVER env var), and I got another error 
```
RuntimeException: Could not start chrome (or it crashed) after 30 seconds.
```

Finally I have to uninstall Chrome and Chrome driver and install Chromium and Chromium driver on the virtual environnement.
```
sudo apt-get update
sudo apt-get remove google-chrome-stable
sudo apt-get install chromium-driver google-chrome-stable
```
and also set this env var on Github Actions:
```
PANTHER_CHROME_DRIVER_BINARY=/usr/lib/chromium-browser/chromedriver
``` 

Anyone in my case? Did you find another way to run Symfony Panther test cases on Github Actions?

**Comment by eislambey** [comment]
you can update pre-installed chrome driver manually with the following commands. i have fixed with this way.
```
cd vendor/symfony/panther/chromedriver-bin
sh update.sh
cd ../../../../
```

**Comment by qdequippe** [comment]
> you can update pre-installed chrome driver manually with the following commands. i have fixed with this way.
> 
> ```
> cd vendor/symfony/panther/chromedriver-bin
> sh update.sh
> cd ../../../../
> ```

Same result :/

**Comment by Lctrs** [comment]
```yaml
      - name: "Run tests with panther"
        env:
          PANTHER_CHROME_ARGUMENTS: "--disable-dev-shm-usage"
          PANTHER_CHROME_DRIVER_BINARY: "/usr/bin/chromedriver"
          PANTHER_NO_SANDBOX: "1"
        run: "your command here"
```

This should be enough.

The `$CHROMEWEBDRIVER` env var is broken. It does not point to the binary as said in the documentation but to the directory containing the binary. Luckily, `/usr/bin/chromedriver` is a symlink that points to the right binary.
