### ISSUE TITLE
Timeout in Gitlab CI

### ISSUE THREAD

**Issue by back-2-95** [symfony/panther#409]
We have Panther 0.9 tests for non-Symfony site.
Image for the job is docker 19.03, docker-dind, mysql, redis and solr are services with aliases.

Job script is like this:

```
  variables:
    PANTHER_NO_SANDBOX: 1
    PANTHER_WEB_SERVER_PORT: 9080
    PANTHER_URL: http://docker

  before_script:
    - apk add --no-cache bind-tools chromium chromium-chromedriver curl
    - apk add --no-cache php7 php7-curl php7-dom php7-json php7-mbstring php7-openssl php7-phar php7-simplexml
    - apk add --no-cache php7-tokenizer php7-xml php7-xmlwriter php7-zip
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php composer-setup.php --install-dir=/usr/local/bin --filename=composer
    - php -r "unlink('composer-setup.php');"
    - which chromium && chromium --version
    - which chromedriver && chromedriver --version
  
  script:

    - composer install --no-progress
    - vendor/bin/bdi detect drivers

    # Load image from build stage artifacts
    - docker load < "${CI_COMMIT_SHA}.tar"

    - gunzip tests/dump.sql.gz

    # Run our app and is then running then at http://docker
    # "docker" is alias for docker service
    - >
        docker run --name app -d -p 80:8080
        --add-host="db:$(dig +short db)"
        --add-host="redis:$(dig +short redis)"
        --add-host="solr:$(dig +short solr)"
        "our_build_app_image_from_previous_stage"

    ... here we prepare the container with CI specific confs and populate database etc ...

    # Just check with curl that PANTHER_URL is accessible (allowing possible redirects)
    - curl -L $PANTHER_URL/en/user
 
    # Run Panther tests
    - vendor/bin/phpunit --stop-on-failure --colors=never
    ```

- Curl will succesfully get output from app container via http://docker

Panther will just give:

```
PHPUnit 9.5.1 by Sebastian Bergmann and contributors.
Create Chrome client with base URL http://docker
Content page
- Login as a Super editor
E
Tear down Chrome client...
Time: 00:32.376, Memory: 8.00 MB
There was 1 error:
1) App\Tests\Admin\CreatePageContentTest::testCreatePageContent
Facebook\WebDriver\Exception\TimeoutException: 
/builds/REPO/PROJECT/vendor/php-webdriver/webdriver/lib/WebDriverWait.php:71
/builds/REPO/PROJECT/vendor/symfony/panther/src/Client.php:332
/builds/REPO/PROJECT/tests/Admin/AdminTestTrait.php:73
/builds/REPO/PROJECT/tests/Admin/AdminTestTrait.php:17
/builds/REPO/PROJECT/tests/Admin/CreatePageContentTest.php:21
ERRORS!
Tests: 1, Assertions: 0, Errors: 1.
```

In unit tests the Panther client is created with:

```
    $base_url = getenv('PANTHER_URL') ?: 'http://app.local';
    self::$_client = static::createPantherClient([
      'external_base_uri' => $base_url,
    ]);
```
