### ISSUE TITLE
Can't enable logging for chromedriver

### ISSUE THREAD

**Issue by QuestionDevelopment** [symfony/panther#567]
Hello everyone,
My script runs perfectly however, I have tried every varation of arguments and I can not get chromedrive to log.  The php-chromedriver dev team is asking for logs to resolve an issue and I can not provide it @ https://github.com/php-webdriver/php-webdriver/issues/1011

```
Panther Version: 2.0.1
Php-webdriver version: 1.12.1
PHP version: PHP 8.1.9
How do you start the browser driver or Selenium server: [Panther](https://github.com/symfony/panther)
Selenium server version: Not used
Chromedriver version: 104.0.5112.79
Browser used + version: CURL
Operating system: Debian 11
```

Code

```
    public function driver()
    {
        require_once $this->directory . 'vendor/autoload.php';
        return \Symfony\Component\Panther\Client::createChromeClient('/var/www/drivers/chromedriver', [
            '--headless',
            '--window-size=1200,1100',
            '--disable-gpu',
            //'--logfile=chromedriver.log',
            //'--verboseLogging=true',
            //'--verbose',
            //'--log-path=chromedriver.log'
            //'--log-level=DEBUG',
            //'--log-path=chromedriver.log'
        ]);
    }
```

I appreciate any help you can provide.

**Comment by QuestionDevelopment** [comment]
I am still unable to get working.  Based off ```chromedriver --help`` and the docs @ https://chromedriver.chromium.org/logging

I'm fairly confident that the commands I need are 

```
www-data@panther:~/drivers$ /var/www/drivers/chromedriver --headless --window-size=1200,1100 --disable-gpu --log-path=chromedriver.log --verbose
```

When I run this via cli it runs perfectly and generates a log file.

I can't get it to happen with your script however. While trying to determine why I found what I believe to be a bug..

~/vendor/symfony/panther/src/ProcessManager/ChromeManager.php


```
    public function start(): WebDriver
    {
        $url = $this->options['scheme'].'://'.$this->options['host'].':'.$this->options['port'];
        if (!$this->process->isRunning()) {
            $this->checkPortAvailable($this->options['host'], $this->options['port']);
            $this->process->start();
            $this->waitUntilReady($this->process, $url.$this->options['path'], 'chrome');
        }

        $capabilities = DesiredCapabilities::chrome();

        foreach ($this->options['capabilities'] as $capability => $value) {
            $capabilities->setCapability($capability, $value);
        }

        if ($this->arguments) {
            $chromeOptions = $capabilities->getCapability(ChromeOptions::CAPABILITY);
            if (null === $chromeOptions) {
                $chromeOptions = new ChromeOptions();
                $capabilities->setCapability(ChromeOptions::CAPABILITY, $chromeOptions);
            }
            $chromeOptions->addArguments($this->arguments);

            if (isset($_SERVER['PANTHER_CHROME_BINARY'])) {
                $chromeOptions->setBinary($_SERVER['PANTHER_CHROME_BINARY']);
            }
        }

        return RemoteWebDriver::create($url, $capabilities, $this->options['connection_timeout_in_ms'] ?? null, $this->options['request_timeout_in_ms'] ?? null);
    }
```

The $chromeOptions only gets assigned to $capabilities if $chromeOptions is null.  The $chromeOptions which receives $this->arguments does not seem to be utilized.

**Comment by robertfausk** [comment]
Hi @QuestionDevelopment!
Have a look at the docs:
https://github.com/symfony/panther#passing-arguments-to-chromedriver

The arguments for the bin are taken from the ```$managerOptions``` parameter:

```PHP
// minimal example when using trait
self::createPantherClient([], [], ['chromedriver_arguments' => ['--log-path=/var/www/html/var/log/chromedriver.log', '--verbose']]);
```

```YML
# minimal example when using robertfausk/behat-panther-extension

        Robertfausk\Behat\PantherExtension: ~
        Behat\MinkExtension:
            javascript_session: javascript
            sessions:
                javascript:
                     panther:
                        manager_options:
                            chromedriver_arguments:
                                - --log-path=/var/www/html/chromedriver.log
                                - --verbose
```
