### ISSUE TITLE
Issues with OAuth2 Authentication

### ISSUE THREAD

**Issue by nina-alin** [symfony/panther#648]
Hello!

I am currently working on implementing end-to-end testing using Panther, but I am facing challenges with OAuth2 authentication specifically for Google. I am attempting to manually set the authentication cookies, but it seems they are not being recognized. I am still redirected to the login page when I try to access protected routes. 

Below is the code I am using:

```php
    protected function createAuthenticatedPantherClient(
        User $user
    ): AbstractBrowser
    {
        $token = new UsernamePasswordToken($user, "main", $user->getRoles());

        $this->client->request('GET', '/login');

        $session = new Session(new MockFileSessionStorage('/srv/var/cache/panther/sessions'));
        $session->set('_security_main', serialize($token));
        $session->save();

        $cookie = new Cookie($session->getName(), $session->getId());
        $this->client->getCookieJar()->set($cookie);

        return $this->client;
    }

    public function testHome()
    {
        $this->databaseTool->loadFixtures([
            AppFixtures::class
        ]);

        $this->userRepository = static::getContainer()->get(UserRepository::class);
        $this->client->createAuthenticatedPantherClient($this->userRepository->findOneBy(['email' => 'test@test.com'])); // user does exist in DB

        $this->client->request('GET', '/');

        $this->client->takeScreenshot("test.png"); // still on login page
    }
```

security.yaml:
```yaml
security:
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator:
                - App\Security\EmailAuthenticator
            logout:
                path: app_logout
    access_control:
        - { path: /login, roles: PUBLIC_ACCESS }
        - { path: /connect/google, roles: PUBLIC_ACCESS }
        - { path: ^/*, roles: IS_AUTHENTICATED }
```

The code above does not work as expected, and I cannot identify the root cause. Despite the similarities to the implementation found in [this PR](https://github.com/symfony/panther/pull/574/files), I am experiencing different behavior.

- Is there a potential issue with the Panther framework, or could there be a mistake in my implementation?
- Are there specific configurations or additional steps I need to consider when using OAuth2 authentication with Panther?

Please not that I am a beginner in the Symfony ecosystem. I discussed this issue with a senior developer at my company, who also recommended that I open this issue for further assistance.

Thank you for your time and support!
